package com.shalenammapride.util

data class AppStrings(
    val appName: String,
    val tagline: String,
    val home: String,
    val meals: String,
    val facilities: String,
    val achievements: String,
    val feedback: String,
    val reports: String,
    val admin: String,
    val adminLogin: String,
    val enterPin: String,
    val incorrectPin: String,
    val submit: String,
    val cancel: String,
    val upload: String,
    val uploadPhoto: String,
    val delete: String,
    val save: String,
    val share: String,
    val shareViaWhatsApp: String,
    val todaysMeal: String,
    val mealMenu: String,
    val noMealsToday: String,
    val schoolFacilities: String,
    val facilityName: String,
    val facilityDescription: String,
    val noFacilities: String,
    val studentStar: String,
    val studentName: String,
    val achievementTitle: String,
    val achievementDescription: String,
    val noAchievements: String,
    val yourName: String,
    val yourMessage: String,
    val submitAnonymously: String,
    val noFeedback: String,
    val feedbackSubmitted: String,
    val announcements: String,
    val noAnnouncements: String,
    val language: String,
    val switchToKannada: String,
    val switchToEnglish: String,
    val loading: String,
    val error: String,
    val retry: String,
    val date: String,
    val description: String,
    val uploadingImage: String,
    val uploadSuccess: String,
    val uploadError: String,
    val adminPanel: String,
    val addMeal: String,
    val addFacility: String,
    val addAchievement: String,
    val addAnnouncement: String,
    val title: String,
    val welcomeTitle: String,
    val welcomeSubtitle: String,
    val viewAll: String,
    val recentUpdates: String,
    val schoolActivities: String,
    val buildingTrust: String,
)

val EnglishStrings = AppStrings(
    appName = "Shale - Namma Pride",
    tagline = "Building trust in government schools",
    home = "Home",
    meals = "Meals",
    facilities = "Facilities",
    achievements = "Achievements",
    feedback = "Feedback",
    reports = "Reports",
    admin = "Admin",
    adminLogin = "Admin Login",
    enterPin = "Enter PIN",
    incorrectPin = "Incorrect PIN. Try again.",
    submit = "Submit",
    cancel = "Cancel",
    upload = "Upload",
    uploadPhoto = "Upload Photo",
    delete = "Delete",
    save = "Save",
    share = "Share",
    shareViaWhatsApp = "Share via WhatsApp",
    todaysMeal = "Today's Meal",
    mealMenu = "Meal Menu",
    noMealsToday = "No meal updates today",
    schoolFacilities = "School Facilities",
    facilityName = "Facility Name",
    facilityDescription = "Facility Description",
    noFacilities = "No facilities added yet",
    studentStar = "Student Star",
    studentName = "Student Name",
    achievementTitle = "Achievement Title",
    achievementDescription = "Achievement Description",
    noAchievements = "No achievements yet",
    yourName = "Your Name (Optional)",
    yourMessage = "Your Message",
    submitAnonymously = "Submit Anonymously",
    noFeedback = "No feedback yet",
    feedbackSubmitted = "Feedback submitted successfully!",
    announcements = "Announcements",
    noAnnouncements = "No announcements",
    language = "Language",
    switchToKannada = "ಕನ್ನಡ",
    switchToEnglish = "English",
    loading = "Loading...",
    error = "Something went wrong",
    retry = "Retry",
    date = "Date",
    description = "Description",
    uploadingImage = "Uploading image...",
    uploadSuccess = "Uploaded successfully!",
    uploadError = "Upload failed. Please try again.",
    adminPanel = "Admin Panel",
    addMeal = "Add Meal Update",
    addFacility = "Add Facility",
    addAchievement = "Add Achievement",
    addAnnouncement = "Add Announcement",
    title = "Title",
    welcomeTitle = "Welcome to Namma Shale",
    welcomeSubtitle = "Transparency & Community Engagement",
    viewAll = "View All",
    recentUpdates = "Recent Updates",
    schoolActivities = "School Activities",
    buildingTrust = "Building trust through transparency",
)

val KannadaStrings = AppStrings(
    appName = "ಶಾಲೆ - ನಮ್ಮ ಹೆಮ್ಮೆ",
    tagline = "ಸರ್ಕಾರಿ ಶಾಲೆಗಳಲ್ಲಿ ವಿಶ್ವಾಸ ಮೂಡಿಸುವುದು",
    home = "ಮುಖಪುಟ",
    meals = "ಊಟ",
    facilities = "ಸೌಲಭ್ಯಗಳು",
    achievements = "ಸಾಧನೆ",
    feedback = "ಪ್ರತಿಕ್ರಿಯೆ",
    reports = "ವರದಿ",
    admin = "ನಿರ್ವಾಹಕ",
    adminLogin = "ನಿರ್ವಾಹಕ ಲಾಗಿನ್",
    enterPin = "PIN ನಮೂದಿಸಿ",
    incorrectPin = "ತಪ್ಪಾದ PIN. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    submit = "ಸಲ್ಲಿಸಿ",
    cancel = "ರದ್ದು",
    upload = "ಅಪ್ಲೋಡ್",
    uploadPhoto = "ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    delete = "ಅಳಿಸಿ",
    save = "ಉಳಿಸಿ",
    share = "ಹಂಚಿಕೊಳ್ಳಿ",
    shareViaWhatsApp = "WhatsApp ಮೂಲಕ ಹಂಚಿಕೊಳ್ಳಿ",
    todaysMeal = "ಇಂದಿನ ಊಟ",
    mealMenu = "ಊಟದ ಮೆನು",
    noMealsToday = "ಇಂದು ಯಾವುದೇ ಊಟದ ನವೀಕರಣಗಳಿಲ್ಲ",
    schoolFacilities = "ಶಾಲಾ ಸೌಲಭ್ಯಗಳು",
    facilityName = "ಸೌಲಭ್ಯದ ಹೆಸರು",
    facilityDescription = "ಸೌಲಭ್ಯದ ವಿವರಣೆ",
    noFacilities = "ಇನ್ನೂ ಯಾವುದೇ ಸೌಲಭ್ಯಗಳಿಲ್ಲ",
    studentStar = "ವಿದ್ಯಾರ್ಥಿ ತಾರೆ",
    studentName = "ವಿದ್ಯಾರ್ಥಿ ಹೆಸರು",
    achievementTitle = "ಸಾಧನೆಯ ಶೀರ್ಷಿಕೆ",
    achievementDescription = "ಸಾಧನೆಯ ವಿವರಣೆ",
    noAchievements = "ಇನ್ನೂ ಯಾವುದೇ ಸಾಧನೆಗಳಿಲ್ಲ",
    yourName = "ನಿಮ್ಮ ಹೆಸರು (ಐಚ್ಛಿಕ)",
    yourMessage = "ನಿಮ್ಮ ಸಂದೇಶ",
    submitAnonymously = "ಅನಾಮಧೇಯವಾಗಿ ಸಲ್ಲಿಸಿ",
    noFeedback = "ಇನ್ನೂ ಯಾವುದೇ ಪ್ರತಿಕ್ರಿಯೆ ಇಲ್ಲ",
    feedbackSubmitted = "ಪ್ರತಿಕ್ರಿಯೆ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!",
    announcements = "ಪ್ರಕಟಣೆಗಳು",
    noAnnouncements = "ಯಾವುದೇ ಪ್ರಕಟಣೆಗಳಿಲ್ಲ",
    language = "ಭಾಷೆ",
    switchToKannada = "ಕನ್ನಡ",
    switchToEnglish = "English",
    loading = "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    error = "ಏನೋ ತಪ್ಪಾಗಿದೆ",
    retry = "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    date = "ದಿನಾಂಕ",
    description = "ವಿವರಣೆ",
    uploadingImage = "ಚಿತ್ರ ಅಪ್ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    uploadSuccess = "ಯಶಸ್ವಿಯಾಗಿ ಅಪ್ಲೋಡ್ ಆಗಿದೆ!",
    uploadError = "ಅಪ್ಲೋಡ್ ವಿಫಲವಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    adminPanel = "ನಿರ್ವಾಹಕ ಫಲಕ",
    addMeal = "ಊಟ ನವೀಕರಣ ಸೇರಿಸಿ",
    addFacility = "ಸೌಲಭ್ಯ ಸೇರಿಸಿ",
    addAchievement = "ಸಾಧನೆ ಸೇರಿಸಿ",
    addAnnouncement = "ಪ್ರಕಟಣೆ ಸೇರಿಸಿ",
    title = "ಶೀರ್ಷಿಕೆ",
    welcomeTitle = "ನಮ್ಮ ಶಾಲೆಗೆ ಸ್ವಾಗತ",
    welcomeSubtitle = "ಪಾರದರ್ಶಕತೆ ಮತ್ತು ಸಮುದಾಯ ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆ",
    viewAll = "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
    recentUpdates = "ಇತ್ತೀಚಿನ ನವೀಕರಣಗಳು",
    schoolActivities = "ಶಾಲಾ ಚಟುವಟಿಕೆಗಳು",
    buildingTrust = "ಪಾರದರ್ಶಕತೆಯ ಮೂಲಕ ವಿಶ್ವಾಸ ಮೂಡಿಸುವುದು",
)
